apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ include "istio.fullname" . }}-tls"
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.crt | b64enc }}
  tls.key: {{ .Values.key | b64enc }}
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: mygateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "{{ include "istio.fullname" . }}-tls"
      hosts:
        - httpbin.example.com
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  hosts:
    - "httpbin.example.com"
  gateways:
    - istio-ingress/mygateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: api-service.default.svc.cluster.local
