apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBuq0HKYSar3PLPfPul3W8HRhJaiQfqNCDojRXk9hqunqxl4xo2zd/RooV+/jzUdQZmujAkYREb23PXh7sWOklN26tyyt5ITdlwA0aBAhuHZIyIAq394xXDDd6HzgbBw8qLb1p/yyZ/bUkGuQFntGSE+yjQUUXraQkqn8+5+iyiEXyptLV5V5LvrbEjrOhk4RAZF7SqMed4sCmrGszEN7Hzb/xxgwRPdeHk8tqEL2SMF1Y7+8nxUGLfcYduJ3Chtxkn1tlaE/RqFHoY8hNl0qecvDplQbNhFzYBFSvIMwKgWGh37PZ8/bmqjb2DZhs/KSSMlaEi7SpWBmj7hFSOP56UofucIS0bUkrsw4wKGOpHxCTe+hjJKV/lqOqG/svFxRsiJnGfAShyd870qHIMCtCGp6Sy4tykElFcfAUjnWyY9bSJi3sYzoj7W9aItR5wcdu0hXm8FFiCQfFliFmY0uOwI5rwogWT6Q+szyHdV3gAap4+JJ8PmzFAY9KwMoNRPk5BsD83F44sehOmF2omVWtUYkCPv+85z5C6BX8XIQrZDkejXLNlq7LGFNQSU0w7ri7Rahb16tBfvoC4CR/L75rG5u1IbatLSA3+o3I47qexWuvha68QaF2EH2sQf3KKIpuGcl9qVrAcQwa0AHREIAtYTYbNMK55WmyTi50mtwQIKJJe0nnsVRYkLPk2WZP+ggorBBZYiQ4enpeigX3ekABf+ulh8A==
    AWS_SECRET_ACCESS_KEY: AgAb9tUdPwt1yPnGCqmqcfAUlJTTrFz3MC5I+zEoVUvhQkkdL6BrGPCSk8sDKmCiFHgQupKo9EVmDG4E6xl3A20RIaHnhRYH5mLITySr0UZWYIS7sXs++u4qbaN4Fyixy4Y/g7CYVok7q1MgX0ctFekpMg9eFRcqX2XPj/f3gs7fu4ZvYCtzGSrGIfEoKXusW7oi7JnaGgSHM2u07irN77VOjoE44C8MrYcdZYXCD+4K9JkCtLy/xWNyKAsLz5PyR/svJXeX4JulQt8eS24CRC7znQ+YW4Oh8+V232HUCKYZx3kiRRayCvlNMb01mu4BxQanT9ivdFqGiAfATIYiirQuNZ2Z3kOuf7mONPfFY2Z4/IepcbHW8kUfpTTy8Eo4hvVnGG7NSR/cBZrIsoN9pnv12jPN3V+77xHGwF1R8PkEoehHDcBb+jfrLcaSPWrLoQutIClIWjqCWSl9svUmQyVJz0MftPRARgNBEY6YgsnJ9DpVgeV4cBhw/rarhz4MUWk5leeAV44L+wIdjaZR0PKaRssy+ALMVBC8RY700o0r94Djas7FTbPBiE6gQgN6/3hPe4F82Eyw8jZN4DZR5oOpCzsOVv0eESFISQRoR1y+j3biqZmT4xQCpP3axhWJFRuLc47p4hAEuHGv7pk7TCYfiGOrmBPElOOOCCkwOk6GAbUX4RQv4NVjrPQIjs1cJE13/e2iRA3+HQQnxUWuRFnVUBbf2aV2FueXzQSSIvMmu9s91VRGQDnr
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
    type: Opaque